"""Stage 4B — Leadership Migration formal owner Golden tests.

Locks the frozen PRD §7.10 "Leadership Migration Numerical Contract (FROZEN)"
against the production owner (``build_leadership_snapshot`` +
``compute_leadership_migration``).  Expected values are hand-fixed from the
contract math, NOT generated by the owner under test.

Covers:
  1. up-day leader           2. down-day leader
  3. contrarian excluded     4. 50% minimal prefix
  5. threshold == 50%        6. tie -> member_id ASC
  7. single member           8. EW None
  9. EW zero                 10. valid empty leader set
  11. full-stable            12. full-replacement
  13. partial overlap        14. leader-set expansion
  15. leader-set contraction 16. previous snapshot unavailable
  17. current snapshot unavailable
  18. empty leader-set transition unavailable
  19. deterministic repeat   20. future leak = 0

The migration owner consumes pre-computed ``LeadershipContributionFacts`` (from
the single Stage-1 owner ``compute_member_leadership_contributions``) — it never
re-derives amount_share or contribution.
"""

from __future__ import annotations

from datetime import date

import pytest

from app.domain.first_pyramid_semantics import Direction, MomentumDirection
from app.domain.review.analysis.leadership_contribution import (
    compute_member_leadership_contributions,
)
from app.domain.review.analysis.leadership_migration import (
    LEADERSHIP_COVERAGE,
    build_leadership_snapshot,
    compute_leadership_migration,
)
from app.domain.review.scope_observation import MemberObservation

pytestmark = pytest.mark.pure_unit


def _m(
    mid: str,
    *,
    return_1d: float | None = None,
    amount: float | None = 100.0,
) -> MemberObservation:
    return MemberObservation(
        member_id=mid,
        price_candidate=True,
        return_1d=return_1d,
        amount=amount,
        trend=Direction.UP,
        swing=Direction.UP,
        internal=Direction.UP,
        momentum=MomentumDirection.EXPANDING,
    )


def _facts(members: list[MemberObservation]):
    return compute_member_leadership_contributions(members)


def _snap(day: str, ew: float | None, members: list[MemberObservation]):
    return build_leadership_snapshot(
        trade_date=day, ew_return=ew, contribution_facts=_facts(members)
    )


# ---------------------------------------------------------------------------
# Layer 1 — snapshot (direction + aligned + coverage leader set)
# ---------------------------------------------------------------------------


def test_up_day_positive_contributor_leads() -> None:
    # EW>0 (up).  A: amount_share=0.5 (amount 50/100), return +0.04 -> contrib
    # 0.02; B: 0.5 * -0.02 = -0.01 (contrarian).  leader set = {A}.
    snap = _snap("2026-01-05", 0.03, [_m("a", return_1d=0.04, amount=50.0),
                                      _m("b", return_1d=-0.02, amount=50.0)])
    assert snap.status == "ready"
    assert snap.direction == 1
    assert snap.leader_ids == ("a",)
    assert snap.leader_set[0].aligned_score == pytest.approx(0.02)


def test_down_day_negative_contributor_leads() -> None:
    # EW<0 (down).  A contributes -0.02 (down-driver), B +0.01 (contrarian).
    snap = _snap("2026-01-05", -0.03, [_m("a", return_1d=-0.04, amount=50.0),
                                       _m("b", return_1d=0.02, amount=50.0)])
    assert snap.status == "ready"
    assert snap.direction == -1
    assert snap.leader_ids == ("a",)          # down-driver is the leader
    assert snap.leader_set[0].aligned_score == pytest.approx(0.02)


def test_contrarian_excluded() -> None:
    # Down scope; only B has a positive raw return (contrarian) -> aligned<0,
    # excluded from leader set -> legitimate empty.
    snap = _snap("2026-01-05", -0.05, [_m("b", return_1d=0.02, amount=100.0)])
    assert snap.status == "ready"
    assert snap.direction == -1
    assert snap.leader_set == ()


def test_fifty_percent_minimal_prefix() -> None:
    # amounts a=b=c=d=25 -> share 0.25 each.
    # returns: a=0.08 b=0.04 c=0.02 d=0.01
    # aligned (up): a=.02 b=.01 c=.005 d=.0025 ; total=.0375
    # 50% = .01875 -> {a,b} (a=.02 alone < .01875? .02 >= .01875 -> actually {a}).
    # Recompute: cumulative a=.02 >= .01875 -> leader set = {a} only.
    members = [
        _m("a", return_1d=0.08, amount=25.0),
        _m("b", return_1d=0.04, amount=25.0),
        _m("c", return_1d=0.02, amount=25.0),
        _m("d", return_1d=0.01, amount=25.0),
    ]
    snap = _snap("2026-01-05", 0.06, members)
    assert snap.status == "ready"
    # a alone explains 0.02/0.0375 = 53% >= 50% -> leader set = {a}.
    assert snap.leader_ids == ("a",)


def test_threshold_exactly_fifty_percent() -> None:
    # Two members each 0.5 share.  a return 0.04 -> .02; b return 0.02 -> .01.
    # total .03; 50% = .015.  cumulative a=.02 >= .015 -> leader set = {a}.
    members = [
        _m("a", return_1d=0.04, amount=50.0),
        _m("b", return_1d=0.02, amount=50.0),
    ]
    snap = _snap("2026-01-05", 0.03, members)
    assert snap.leader_ids == ("a",)
    assert snap.status == "ready"


def test_tie_member_id_asc() -> None:
    # Equal contributions -> deterministic member_id ASC.
    # amounts a=100 b=100 -> total 200 -> shares 0.5 each.
    # a return 0.04 -> .02; b return 0.04 -> .02 (tie).  Up scope.
    members = [_m("b", return_1d=0.04, amount=100.0), _m("a", return_1d=0.04, amount=100.0)]
    snap = _snap("2026-01-05", 0.04, members)
    assert snap.status == "ready"
    # Tie -> member_id ASC.  a and b both contribute 0.02; total 0.04, 50%=0.02,
    # so the minimal prefix is {a} (a alone reaches 50%); a before b.
    assert snap.leader_ids[0] == "a"


def test_single_member() -> None:
    snap = _snap("2026-01-05", 0.01, [_m("x", return_1d=0.01, amount=100.0)])
    assert snap.status == "ready"
    assert snap.leader_ids == ("x",)
    assert len(snap.leader_ids) == 1


def test_ew_none_unavailable() -> None:
    snap = _snap("2026-01-05", None, [_m("a", return_1d=0.02, amount=100.0)])
    assert snap.status == "unavailable"
    assert snap.reason == "ew_unavailable"
    assert snap.leader_set is None


def test_ew_zero_unavailable() -> None:
    snap = _snap("2026-01-05", 0.0, [_m("a", return_1d=0.0, amount=100.0)])
    assert snap.status == "unavailable"
    assert snap.reason == "no_prevailing_direction"
    assert snap.leader_set is None


def test_valid_empty_leader_set_distinct_from_none() -> None:
    # Valid EW direction but no aligned>0 -> leader_set == [] (NOT None).
    snap = _snap("2026-01-05", -0.03, [_m("a", return_1d=0.05, amount=100.0)])
    assert snap.status == "ready"
    assert snap.leader_set == ()
    assert snap.leader_set is not None


# ---------------------------------------------------------------------------
# Layer 2 — migration
# ---------------------------------------------------------------------------


def _snap_from_ids(
    day: str, ids: tuple[str, ...], *, direction: int = 1, rankable: int = 0
):
    """Build a ready LeadershipSnapshot with an EXPLICIT leader set (Layer-2 math)."""
    from app.domain.review.analysis.leadership_migration import LeadershipSnapshot

    return LeadershipSnapshot(
        trade_date=day,
        status="ready",
        reason=None,
        direction=direction,
        rankable_count=rankable,
        leader_set=tuple(
            type("AL", (), {"member_id": mid, "contribution": 0.0, "aligned_score": 0.0})()
            for mid in ids
        ),
    )


def test_full_stable() -> None:
    # Same leader set both days -> Jaccard=1, Migration=0, Retention=1.
    prev = _snap_from_ids("2026-01-04", ("a", "b", "c"))
    curr = _snap_from_ids("2026-01-05", ("a", "b", "c"))
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "ready"
    assert facts.jaccard_stability == pytest.approx(1.0)
    assert facts.migration == pytest.approx(0.0)
    assert facts.previous_retention == pytest.approx(1.0)
    assert facts.retained_count == 3
    assert facts.entrant_count == 0
    assert facts.exit_count == 0


def test_full_replacement() -> None:
    prev = _snap_from_ids("2026-01-04", ("a",))
    curr = _snap_from_ids("2026-01-05", ("z",))
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "ready"
    assert facts.jaccard_stability == pytest.approx(0.0)
    assert facts.migration == pytest.approx(1.0)
    assert facts.previous_retention == pytest.approx(0.0)
    assert facts.entrant_ids == ("z",)
    assert facts.exit_ids == ("a",)


def test_partial_overlap() -> None:
    # prev {a,b,c}, curr {a,b,d}: retained {a,b}; entrant {d}; exit {c}.
    prev = _snap_from_ids("2026-01-04", ("a", "b", "c"))
    curr = _snap_from_ids("2026-01-05", ("a", "b", "d"))
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "ready"
    assert facts.retained_count == 2
    assert facts.entrant_count == 1
    assert facts.exit_count == 1
    assert facts.jaccard_stability == pytest.approx(2 / 4)
    assert facts.migration == pytest.approx(1 - 2 / 4)
    assert facts.previous_retention == pytest.approx(2 / 3)


def test_leader_set_expansion() -> None:
    # prev {a,b}, curr {a,b,c,d,e,f}: Jaccard = 2/6; retention blind to expansion.
    prev = _snap_from_ids("2026-01-04", ("a", "b"))
    curr = _snap_from_ids("2026-01-05", ("a", "b", "c", "d", "e", "f"))
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "ready"
    assert facts.previous_leader_count == 2
    assert facts.current_leader_count == 6
    assert facts.retained_count == 2
    assert facts.jaccard_stability == pytest.approx(2 / 6)
    assert facts.previous_retention == pytest.approx(2 / 2)  # retention blind to expansion


def test_leader_set_contraction() -> None:
    # prev {a,b,c}, curr {a}: Jaccard = 1/3.
    prev = _snap_from_ids("2026-01-04", ("a", "b", "c"))
    curr = _snap_from_ids("2026-01-05", ("a",))
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "ready"
    assert facts.jaccard_stability == pytest.approx(1 / 3)
    assert facts.migration == pytest.approx(1 - 1 / 3)
    assert facts.exit_ids == ("b", "c")


def test_previous_snapshot_unavailable() -> None:
    prev = _snap("2026-01-04", None, [_m("a", return_1d=0.02, amount=100.0)])
    curr = _snap("2026-01-05", 0.03, [_m("a", return_1d=0.02, amount=100.0)])
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "unavailable"
    assert facts.reason == "unavailable_snapshot"
    assert facts.migration is None
    assert facts.jaccard_stability is None


def test_current_snapshot_unavailable() -> None:
    prev = _snap("2026-01-04", 0.03, [_m("a", return_1d=0.02, amount=100.0)])
    curr = _snap("2026-01-05", 0.0, [_m("a", return_1d=0.02, amount=100.0)])
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "unavailable"
    assert facts.reason == "unavailable_snapshot"


def test_empty_leader_set_transition_unavailable() -> None:
    # prev valid-empty (no aligned>0), curr normal.  Fail-closed unavailable.
    prev = _snap("2026-01-04", -0.03, [_m("b", return_1d=0.05, amount=100.0)])
    curr = _snap("2026-01-05", 0.03, [_m("a", return_1d=0.02, amount=100.0)])
    assert prev.status == "ready"
    assert prev.leader_set == ()           # valid empty, NOT None
    facts = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert facts.status == "unavailable"
    assert facts.reason == "empty_leader_set"
    assert facts.migration is None


def test_deterministic_repeat() -> None:
    members = [_m("c", return_1d=0.03, amount=33.3),
               _m("a", return_1d=0.05, amount=33.3),
               _m("b", return_1d=0.04, amount=33.3)]
    snap1 = _snap("2026-01-05", 0.04, members)
    snap2 = _snap("2026-01-05", 0.04, members)
    assert snap1.leader_ids == snap2.leader_ids
    facts1 = compute_leadership_migration(
        previous_snapshot=snap1, current_snapshot=snap2, trade_date="2026-01-05"
    )
    facts2 = compute_leadership_migration(
        previous_snapshot=snap1, current_snapshot=snap2, trade_date="2026-01-05"
    )
    assert facts1 == facts2


def test_future_leak_zero() -> None:
    # compute_leadership_migration must only read T-1 and T — mutating T+1 data
    # (an unrelated later snapshot) must not change the T-1/T result.
    prev = _snap("2026-01-04", 0.03, [_m("a", return_1d=0.05, amount=50.0),
                                      _m("b", return_1d=0.04, amount=50.0)])
    curr = _snap("2026-01-05", 0.03, [_m("a", return_1d=0.05, amount=50.0),
                                      _m("c", return_1d=0.04, amount=50.0)])
    before = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    # A "T+1" snapshot (next day) must not affect the T-1/T comparison.
    future = _snap("2026-01-06", 0.03, [_m("z", return_1d=0.09, amount=100.0)])
    _ = compute_leadership_migration(
        previous_snapshot=curr, current_snapshot=future, trade_date="2026-01-06"
    )
    after = compute_leadership_migration(
        previous_snapshot=prev, current_snapshot=curr, trade_date="2026-01-05"
    )
    assert before == after


def test_coverage_constant_is_050() -> None:
    assert LEADERSHIP_COVERAGE == 0.50
