"""DYNAMICS-LOGIC-CLOSURE — synthetic Golden cases with PRD-fixed expected values.

This is NOT a duplicate of the existing durable owner tests.  Those already prove
the frozen math comprehensively (see test_review_historical_dynamics.py /
test_review_dynamics_phase.py / test_review_scope_dynamics.py).  This file closes
the *explicit* Golden-audit gaps the closure plan calls out:

- OS-1  : continuous timeline order preserved, no silent sort / dedupe / no
          re-interpretation of L1 (Builder output axis == input axis).
- POS-1 : Historical Position percentile hand-computed on a tiny series
          (below_or_equal / n * 100, clamped 0..100), PRD §7.9.
- POS-3 : 120D rolling boundary — T125 uses only the PRD 120-observation window;
          mutating observations 1..4 that have rolled out must NOT change T125.
- EMA5/EMA20 : exact hand-computed recursion (alpha=2/(N+1); first-valid seed;
          warmup at 5th / 20th valid) on a small ready Position series.
- Velocity / Acceleration : hand-computed on the same fixture
          (Velocity = EMA5(Position) - EMA20(Position);
          Signal = EMA5(Velocity); Acceleration = Velocity - Signal).
- Composition equivalence : formal `compute_scope_dynamics_analysis` output equals
          the canonical owners called in sequence, over a REAL canonical payload.

Every expected value below is written by hand from the PRD math contract, NOT
generated by the production functions under test.
"""

from __future__ import annotations

import math
from datetime import date, timedelta
from typing import Any

import pytest

from app.domain.first_pyramid_semantics import Direction, MomentumDirection
from app.domain.review.analysis.dynamics_phase import compute_dynamics_phase_series
from app.domain.review.analysis.historical_dynamics import (
    STATUS_INSUFFICIENT,
    STATUS_READY,
    compute_historical_dynamics_series,
)
from app.domain.review.analysis.historical_position import (
    compute_position_series_from_primitive_series,
)
from app.domain.review.analysis.observation_series import build_observation_series
from app.domain.review.analysis.scope_dynamics import (
    DYNAMICS_PHASE_PRIMITIVE_KEY,
    compute_scope_dynamics_analysis,
)
from app.domain.review.scope_evidence import percentile_rank
from app.domain.review.scope_observation import (
    MemberObservation,
    compute_scope_observation,
)

pytestmark = pytest.mark.pure_unit


def _trading_days(start: date, count: int) -> list[date]:
    """Return ``count`` ascending weekdays starting at ``start``."""
    out: list[date] = []
    d = start
    while len(out) < count:
        if d.weekday() < 5:
            out.append(d)
        d += timedelta(days=1)
    return out


def _position_fact(
    td: date,
    position: float | None,
    status: str,
) -> dict[str, Any]:
    """A Position fact in the exact shape produced by ``compute_position_series``."""
    return {
        "primitive_key": "equal_weight_return",
        "trade_date": td.isoformat(),
        "value": position,
        "position": position,
        "history": {
            "window_size": 120,
            "minimum_valid_history": 60,
            "candidate_count": 60,
            "valid_count": 60,
        },
        "status": status,
    }


def _ready_position_series(values: list[float]) -> list[dict[str, Any]]:
    days = _trading_days(date(2026, 1, 5), len(values))
    return [_position_fact(d, v, STATUS_READY) for d, v in zip(days, values, strict=True)]


# ---------------------------------------------------------------------------
# OS-1 — ObservationSeries timeline order / no sort / no dedupe
# ---------------------------------------------------------------------------


def _real_series_item(
    trade_date: date,
    ret: float,
    amount: float = 1e6,
) -> dict[str, Any]:
    member = MemberObservation(
        member_id="m1",
        price_candidate=True,
        return_1d=ret,
        amount=amount,
        trend=Direction.UP,
        swing=Direction.UP,
        internal=Direction.UP,
        momentum=MomentumDirection.EXPANDING,
        regime_strength=0.5,
        vol_ratio20=1.0,
        vol_ratio200=2.0,
    )
    payload = compute_scope_observation(
        scope_type="industry",
        scope_key="electronics",
        trade_date=trade_date,
        pit_member_ids=["m1"],
        members=[member],
        event_coverage_member_ids=None,
    )
    return {"trade_date": trade_date.isoformat(), "observation": payload}


def test_os1_continuous_timeline_order_preserved_no_sort_no_dedupe() -> None:
    """OS-1: a continuous, non-monotonic value timeline flows through the Builder
    with its date order preserved — no silent sort, no dedupe, no re-interpretation
    of the L1 payload."""
    days = _trading_days(date(2026, 1, 5), 8)
    values = [0.01, 0.03, -0.02, 0.05, 0.00, 0.02, -0.01, 0.04]
    raw = [
        _real_series_item(d, ret=v)
        for d, v in zip(days, values, strict=True)
    ]
    obs_series = build_observation_series(
        scope_type="industry",
        scope_key="electronics",
        from_date=days[0],
        to_date=days[-1],
        trading_dates=days,
        snapshot_series=[
            {"trade_date": d.isoformat(), "readiness": "ready", "payload": p["observation"]}
            for d, p in zip(days, raw, strict=True)
        ],
    )
    ew = obs_series["primitives"][DYNAMICS_PHASE_PRIMITIVE_KEY]
    ew_points = ew["points"]
    # Date axis == input axis (ascending, full length, no compression / dedupe).
    assert [p["trade_date"] for p in ew_points] == [d.isoformat() for d in days]
    assert len(ew_points) == len(days)
    # EW primitive equals the equal-weighted member return at each day.
    for p, v in zip(ew_points, values, strict=True):
        assert p["value"] == pytest.approx(v)


# ---------------------------------------------------------------------------
# POS-1 — Historical Position percentile hand-computed (PRD §7.9)
# ---------------------------------------------------------------------------


def test_pos1_percentile_hand_computed() -> None:
    """POS-1: with a known pre-T baseline, Position(T) = percentile_rank(T,
    valid_preT) = below_or_equal / n * 100, clamped to 0..100."""
    # baseline = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] (10 valid pre-T samples).
    baseline = [float(v) for v in range(1, 11)]
    # value = 5 -> 5 values <= 5 (1..5) of 10 -> 50.
    assert percentile_rank(5.0, baseline) == pytest.approx(50.0)
    # value = 1 -> 1 value <= 1 of 10 -> 10.
    assert percentile_rank(1.0, baseline) == pytest.approx(10.0)
    # value = 10 -> 10 values <= 10 -> 100 (clamped inclusive).
    assert percentile_rank(10.0, baseline) == pytest.approx(100.0)
    # value = 0 -> 0 values <= 0 -> 0.
    assert percentile_rank(0.0, baseline) == pytest.approx(0.0)


def test_pos1_percentile_ties_all_count() -> None:
    """Tie behavior: values equal to T all count toward below_or_equal."""
    baseline = [5.0, 5.0, 10.0]
    assert percentile_rank(5.0, baseline) == pytest.approx(2 / 3 * 100)
    assert percentile_rank(7.0, baseline) == pytest.approx(2 / 3 * 100)


# ---------------------------------------------------------------------------
# POS-3 — 120D rolling boundary
# ---------------------------------------------------------------------------


def _full_ready_position_series(count: int, base: float = 10.0) -> list[dict[str, Any]]:
    days = _trading_days(date(2026, 1, 5), count)
    return [_position_fact(d, base + (i % 7), STATUS_READY) for i, d in enumerate(days)]


def test_pos3_120d_rolling_boundary_t125_unaffected_by_rolled_out() -> None:
    """POS-3: on a >120-day ready series, T at index 124 uses only the latest 120
    candidate slots before it.  Mutating observations 1..4 (already rolled out of
    the 120-window) must leave Position(124) bit-identical."""
    count = 126  # indices 0..125; T125 = index 124
    base = _full_ready_position_series(count)
    t = 124
    before = compute_position_series_from_primitive_series(
        _to_primitive_series(base)
    )[t]

    mutated = list(base)
    # T125 (index 124) baseline = latest 120 slots before it = indices [4, 123].
    # Indices 0..3 have rolled out of the window, so mutating them (first 4)
    # must leave T125 bit-identical.
    for i in (0, 1, 2, 3):
        mutated[i] = _position_fact(date.fromisoformat(base[i]["trade_date"]), 999.0, STATUS_READY)
    after = compute_position_series_from_primitive_series(_to_primitive_series(mutated))[t]
    assert after == before


def _to_primitive_series(position_series: list[dict[str, Any]]) -> dict[str, Any]:
    """Wrap Position facts into the formal PrimitiveSeries shape
    (``primitives[key]`` = ``{"key", "points"}`` with per-point
    ``{"trade_date", "readiness", "value", "available"}``) that
    ``compute_position_series_from_primitive_series`` consumes.  ``readiness`` maps
    from the Position status so the Position window / percentile logic sees the
    same availability the canonical chain would."""
    return {
        "key": DYNAMICS_PHASE_PRIMITIVE_KEY,
        "points": [
            {
                "trade_date": f["trade_date"],
                "readiness": (
                    "ready"
                    if f["status"] == STATUS_READY
                    else "unavailable"
                ),
                "value": f["position"],
                "available": f["position"] is not None,
            }
            for f in position_series
        ],
    }


# ---------------------------------------------------------------------------
# EMA5 / EMA20 exact numerical (alpha = 2/(N+1); first-valid seed; warmup)
# ---------------------------------------------------------------------------


def test_ema5_exact_values() -> None:
    """EMA5 on ready positions 10,20,30,40,50,60.  alpha = 2/6 = 1/3.
    Hand recursion (state s): s1=10; s2=40/3; s3=170/9; s4=... ; s5 (5th valid,
    first ready) and s6 hand-computed below."""
    values = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0]
    pos = _ready_position_series(values)
    chain = compute_historical_dynamics_series(pos)
    ema5 = chain["ema5"]

    # Warmup: first 4 valid inputs -> insufficient_history (value None).
    for i in range(4):
        assert ema5[i]["status"] == STATUS_INSUFFICIENT
        assert ema5[i]["value"] is None
    # 5th valid -> first ready.
    assert ema5[4]["status"] == STATUS_READY
    # Exact state after the recursion:
    #   s1 = 10
    #   s2 = (20 + 2*10)/3 = 40/3 = 13.3333
    #   s3 = (30 + 2*(40/3))/3 = (30 + 80/3)/3 = (90+80)/9 = 170/9 = 18.8889
    #   s4 = (40 + 2*(170/9))/3 = (360/9 + 340/9)/3 = (700/9)/3 = 700/27 = 25.9259
    #   s5 = (50 + 2*(700/27))/3 = (1350/27 + 1400/27)/3 = (2750/27)/3 = 2750/81 = 33.9506
    #   s6 = (60 + 2*(2750/81))/3 = (4860/81 + 5500/81)/3 = (10360/81)/3 = 10360/243 = 42.6337
    assert ema5[4]["value"] == pytest.approx(2750 / 81, abs=1e-9)
    assert ema5[5]["value"] == pytest.approx(10360 / 243, abs=1e-9)
    # valid_count reflects the number of valid inputs consumed.
    assert ema5[4]["valid_count"] == 5
    assert ema5[5]["valid_count"] == 6


def test_ema20_warmup_at_20th_valid() -> None:
    """EMA20: 19th valid input -> insufficient_history; 20th valid -> first ready.
    alpha = 2/21.  State stays at seed 10 for constant input; the first ready value
    equals the seed (10.0) because every input is identical."""
    values = [10.0] * 22
    pos = _ready_position_series(values)
    chain = compute_historical_dynamics_series(pos)
    ema20 = chain["ema20"]
    assert ema20[18]["status"] == STATUS_INSUFFICIENT  # 19th valid
    assert ema20[18]["value"] is None
    assert ema20[19]["status"] == STATUS_READY  # 20th valid
    # Constant input -> EMA stays at the seed value.
    assert ema20[19]["value"] == pytest.approx(10.0, abs=1e-9)
    assert ema20[19]["valid_count"] == 20


def test_ema20_exact_jump_blend() -> None:
    """EMA20 exact blend after 20 identical seeds then one jump:
    state = (2/21)*jump + (19/21)*seed."""
    values = [10.0] * 20 + [25.0]
    pos = _ready_position_series(values)
    chain = compute_historical_dynamics_series(pos)
    ema20 = chain["ema20"]
    assert ema20[20]["status"] == STATUS_READY
    assert ema20[20]["value"] == pytest.approx((2 / 21) * 25.0 + (19 / 21) * 10.0, abs=1e-9)


# ---------------------------------------------------------------------------
# Velocity / Acceleration exact (Velocity = EMA5 - EMA20; Signal = EMA5(Velocity);
# Acceleration = Velocity - Signal)
# ---------------------------------------------------------------------------


def _chain_at(chain: dict[str, list[dict[str, Any]]], key: str, i: int) -> Any:
    return chain[key][i]


def test_velocity_and_acceleration_exact() -> None:
    """On a fully-warm ready Position series, at a chosen index T:
      Velocity(T) = EMA5(Position)(T) - EMA20(Position)(T);
      Signal(T)  = EMA5(Velocity)(T);
      Acceleration(T) = Velocity(T) - Signal(T).
    The values are hand-derived from the frozen recursion (independent of the
    production outputs), then asserted exactly."""
    # A deterministic, slowly-increasing ready Position series large enough that
    # EMA5, EMA20, Velocity, Signal (EMA5 of Velocity) and Acceleration are all
    # ready at the tail.  Use a hand-verified recursion oracle carried forward.
    values = [10.0 + 0.5 * i for i in range(120)]
    pos = _ready_position_series(values)
    chain = compute_historical_dynamics_series(pos)

    # First, build an independent incremental EMA oracle to fix expected numbers.
    def _ema_series(inputs: list[tuple[float | None, str]], span: int) -> list[float | None]:
        alpha = 2.0 / (span + 1.0)
        state: float | None = None
        valid = 0
        out: list[float | None] = []
        for value, status in inputs:
            if status == STATUS_READY:
                assert value is not None and math.isfinite(value)
                state = value if state is None else alpha * value + (1.0 - alpha) * state
                valid += 1
                out.append(state if valid >= span else None)
            else:
                out.append(None)
        return out

    inputs = [(f["position"], f["status"]) for f in pos]
    pos_vals = [f["position"] for f in pos]
    ema5_exp = _ema_series(inputs, 5)
    ema20_exp = _ema_series(inputs, 20)
    vel_exp = [
        (e5 - e20) if (e5 is not None and e20 is not None) else None
        for e5, e20 in zip(ema5_exp, ema20_exp, strict=True)
    ]
    vel_inputs = [(v, "ready" if v is not None else STATUS_INSUFFICIENT) for v in vel_exp]
    signal_exp = _ema_series(vel_inputs, 5)
    acc_exp = [
        (v - s) if (v is not None and s is not None) else None
        for v, s in zip(vel_exp, signal_exp, strict=True)
    ]

    # Position series is trusted; assert it equals the input values.
    assert pos_vals == values
    # EMA5 / EMA20 series match the independent oracle at every index.
    assert [f["value"] for f in chain["ema5"]] == ema5_exp
    assert [f["value"] for f in chain["ema20"]] == ema20_exp
    # Velocity = EMA5 - EMA20.
    assert [f["value"] for f in chain["velocity"]] == vel_exp
    # Signal = EMA5(Velocity); Acceleration = Velocity - Signal.
    assert [f["value"] for f in chain["signal"]] == signal_exp
    assert [f["value"] for f in chain["acceleration"]] == acc_exp

    # Spot-check hand-computed exact numbers at a fully-warm tail index (e.g. 100).
    t = 100
    assert chain["velocity"][t]["value"] == pytest.approx(vel_exp[t], abs=1e-12)
    assert chain["acceleration"][t]["value"] == pytest.approx(acc_exp[t], abs=1e-12)


# ---------------------------------------------------------------------------
# Composition equivalence (formal composition == canonical owners in sequence)
# ---------------------------------------------------------------------------


def _returns(count: int) -> list[float]:
    return [0.012 * math.sin(i / 12) + 0.0015 * ((i * 7) % 5 - 2) for i in range(count)]


def test_composition_equivalence_over_real_payload() -> None:
    """Composition equivalence: ``compute_scope_dynamics_analysis`` (formal) equals
    calling the canonical owners in sequence over a real canonical L1 payload."""
    days = _trading_days(date(2026, 1, 5), 130)
    raw = [_real_series_item(d, ret=r) for d, r in zip(days, _returns(130), strict=True)]
    obs_series = build_observation_series(
        scope_type="industry",
        scope_key="electronics",
        from_date=days[0],
        to_date=days[-1],
        trading_dates=days,
        snapshot_series=[
            {"trade_date": d.isoformat(), "readiness": "ready", "payload": p["observation"]}
            for d, p in zip(days, raw, strict=True)
        ],
    )

    composed = compute_scope_dynamics_analysis(obs_series)

    ew = obs_series["primitives"][DYNAMICS_PHASE_PRIMITIVE_KEY]
    pos = compute_position_series_from_primitive_series(ew)
    hd = compute_historical_dynamics_series(pos)
    ph = compute_dynamics_phase_series(hd)

    assert composed["historical_dynamics"] == hd
    assert composed["dynamics_phase"] == ph
    assert composed["primitive_key"] == DYNAMICS_PHASE_PRIMITIVE_KEY
